# -*- coding: utf-8 -*-
"""Day_01_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7MBogE_CVglmNjgTdMrBjUGYQK0HunP

# DAY 1 TASKS - OPERATORS, CONDITIONS

# Task 01: Employee Salary Calculator (Arithmetic Operator)
# Scenario: calculate monthly salary after bonus and tax
"""

print("Task 01: Employee Salary Calculator")

basic_salary = 40000
bonus = 5000
tax_percent = 10

gross_salary = basic_salary + bonus
tax_amount = (gross_salary * tax_percent) / 100
net_salary = gross_salary - tax_amount

print("Basic Salary:", basic_salary)
print("Bonus:", bonus)
print("Gross Salary:", gross_salary)
print("Tax Amount:", tax_amount)
print("Net Monthly Salary:", net_salary)

print("\n" + "-"*60 + "\n")

"""# Task 02: Internship Eligibility Checker
# (Comparison + Logical Operators)
# Scenario: check eligibility based on cgpa and year
"""

print("Task 02: Internship Eligibility Checker")

cgpa = 7.2
year = 3

if cgpa >= 7.0 and year >= 3:
    print("Eligible for Internship ✅")
else:
    print("Not Eligible for Internship ❌")

print("\n" + "-"*60 + "\n")

"""# Task 03: Login Authentication System
# (Logical + Conditional Statement)
# Scenario: validate the user login credentials
"""

print("Task 03: Login Authentication System")

correct_username = "tarun"
correct_password = "1234"

entered_username = "tarun"
entered_password = "1234"

if entered_username == correct_username and entered_password == correct_password:
    print("Login Successful ✅")
else:
    print("Login Failed ❌")

print("\n" + "-"*60 + "\n")

"""# Task 04: Shopping Discount Engine
# (Assignment Operator)
# Scenario: apply the discount to the total amount
"""

print("Task 04: Shopping Discount Engine")

total_amount = 8000
discount_percent = 10

print("Original Amount:", total_amount)

discount_value = (total_amount * discount_percent) / 100

# Assignment operator usage
total_amount -= discount_value

print("Discount Applied:", discount_value)
print("Final Amount after Discount:", total_amount)

print("\n" + "-"*60 + "\n")

"""# Task 05: Course Enrollment Validator
# (Membership Operator + Conditional Statement)
# Scenario: check if student enrolled in python course
"""

print("Task 05: Course Enrollment Validator")

enrolled_courses = ["Java", "Python", "C++", "SQL"]
student_course = "Python"

if student_course in enrolled_courses:
    print("Student is enrolled in Python course ✅")
else:
    print("Student is NOT enrolled in Python course ❌")

print("\n" + "-"*60 + "\n")

"""# Task 06: Role Verification System
# (Identity Operator + Conditional Statement)
# Scenario: check if user role object is admin at execution time
"""

print("Task 06: Role Verification System")

admin_role = "admin"
user_role = "admin"

# identity operator (is)
if user_role is admin_role:
    print("User role is ADMIN ✅")
else:
    print("User role is NOT ADMIN ❌")

print("\n" + "-"*60 + "\n")

"""# Task 07: Even-Odd Transaction Checker
# (Modulus Operator)
# Scenario: check if transaction id is even or odd
"""

print("Task 07: Even-Odd Transaction Checker")

transaction_id = 20261

if transaction_id % 2 == 0:
    print("Transaction ID is EVEN ✅")
else:
    print("Transaction ID is ODD ✅")

print("\n" + "-"*60 + "\n")

"""# MINI PROJECT: Performance Rating System
# (Conditional Statement)
# Scenario: assign performance rating
"""

print("Mini Project: Performance Rating System")

performance_score = 78

if performance_score >= 90:
    rating = "Outstanding ⭐⭐⭐⭐⭐"
elif performance_score >= 75:
    rating = "Excellent ⭐⭐⭐⭐"
elif performance_score >= 60:
    rating = "Good ⭐⭐⭐"
elif performance_score >= 40:
    rating = "Average ⭐⭐"
else:
    rating = "Needs Improvement ⭐"

print("Performance Score:", performance_score)
print("Performance Rating:", rating)

print("\n✅ ALL TASKS COMPLETED SUCCESSFULLY!")