# -*- coding: utf-8 -*-
"""Day_03_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fOSvr4C2khnlMtD-45-Dws6tqO2RYXn

# DAY 2 TASKS - FUNCTIONS, LISTS, CONDITIONS

# Task 01: Student Grade Calculator
# Function: calculate_grade(marks)
# Input: list of marks
# Output: Grade (A, B, C, Fail)
# Topics: functions, lists, conditional statements
"""

def calculate_grade(marks):
    if len(marks) == 0:
        return "Fail"  # no marks means fail

    avg = sum(marks) / len(marks)

    if avg >= 80:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 40:
        return "C"
    else:
        return "Fail"


print("Task 01: Student Grade Calculator")
marks_list = [78, 85, 90, 72]
grade = calculate_grade(marks_list)

print("Marks:", marks_list)
print("Grade:", grade)

print("\n" + "-"*60 + "\n")

"""# Task 02: ATM Withdrawal Function
# Function: withdraw(balance, amount)
# Check:
# - amount <= balance
# - amount is multiple of 100
# Return updated balance
"""

def withdraw(balance, amount):
    if amount <= 0:
        return balance, "Invalid withdrawal amount ❌"

    if amount > balance:
        return balance, "Insufficient balance ❌"

    if amount % 100 != 0:
        return balance, "Amount must be a multiple of 100 ❌"

    balance -= amount
    return balance, "Withdrawal successful ✅"


print("Task 02: ATM Withdrawal Function")

balance = 5000
amount = 1200

new_balance, message = withdraw(balance, amount)

print("Old Balance:", balance)
print("Withdraw Amount:", amount)
print(message)
print("New Balance:", new_balance)

print("\n" + "-"*60 + "\n")

"""# Task 03: Password Validator
# Requirements:
# - min 8 characters
# - at least 1 digit
# - at least 1 uppercase letter
"""

def validate_password(password):
    if len(password) < 8:
        return False, "Password must be at least 8 characters ❌"

    has_digit = False
    has_upper = False

    for ch in password:
        if ch.isdigit():
            has_digit = True
        if ch.isupper():
            has_upper = True

    if not has_digit:
        return False, "Password must contain at least 1 digit ❌"
    if not has_upper:
        return False, "Password must contain at least 1 uppercase letter ❌"

    return True, "Password is valid ✅"


print("Task 03: Password Validator")

password = "Tarun123"
is_valid, msg = validate_password(password)

print("Password:", password)
print(msg)

print("\n" + "-"*60 + "\n")

"""# Task 04: Employee Salary Calculator
# Requirements:
# - hra = 20%
# - pf = 12%
# return net salary
"""

def net_salary(basic_salary):
    hra = basic_salary * 0.20
    pf = basic_salary * 0.12

    gross_salary = basic_salary + hra
    net = gross_salary - pf

    return net


print("Task 04: Employee Salary Calculator")

basic_salary = 40000
final_salary = net_salary(basic_salary)

print("Basic Salary:", basic_salary)
print("Net Salary:", final_salary)

print("\n" + "-"*60 + "\n")

"""# Task 05: File Data Counter
# Requirements:
# function to count:
# - lines
# - words
# - characters
"""

def file_data_counter(filename):
    try:
        with open(filename, "r", encoding="utf-8") as file:
            text = file.read()

        lines = text.split("\n")
        words = text.split()
        characters = len(text)

        return len(lines), len(words), characters

    except FileNotFoundError:
        return None, None, None


print("Task 05: File Data Counter")

"""# Creating a sample file for testing"""

sample_file = "sample.txt"
with open(sample_file, "w", encoding="utf-8") as f:
    f.write("Hello Tarun\nWelcome to Python\nThis is Day 2 tasks")

line_count, word_count, char_count = file_data_counter(sample_file)

print("File:", sample_file)
print("Lines:", line_count)
print("Words:", word_count)
print("Characters:", char_count)

print("\n✅ ALL TASKS COMPLETED SUCCESSFULLY!")