# -*- coding: utf-8 -*-
"""Day_04_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D56vPFH1QX-UrUzFc6Y87vLrn-VGmDcM

# DAY 4 TASKS - FILE HANDLING + EXCEPTION HANDLING

# Helper: Create sample files
"""

def create_sample_files():
    # Sample log file for Task 01
    with open("system.log", "w", encoding="utf-8") as f:
        f.write("INFO: System started\n")
        f.write("ERROR: Database connection failed\n")
        f.write("WARNING: Low memory\n")
        f.write("ERROR: Disk not found\n")
        f.write("INFO: Retry connection\n")
        f.write("ERROR: Timeout occurred\n")

    # Sample employees csv for Task 02
    with open("employees.csv", "w", encoding="utf-8") as f:
        f.write("name,department,salary\n")
        f.write("Tarun,IT,75000\n")
        f.write("Rahul,HR,42000\n")
        f.write("Neha,Finance,90000\n")
        f.write("Animesh,IT,65000\n")
        f.write("Sneha,Sales,30000\n")

create_sample_files()
print("📁 Sample files created: system.log, employees.csv\n")

"""# TASK 01:
# count the number of errors
# store the error lines separately
"""

print("Task 01: Error Counter + Store Error Lines")

def count_and_store_errors(log_filename, output_filename="error_lines.txt"):
    error_lines = []
    error_count = 0

    try:
        with open(log_filename, "r", encoding="utf-8") as file:
            for line in file:
                if "ERROR" in line:
                    error_count += 1
                    error_lines.append(line.strip())

        # store separately
        with open(output_filename, "w", encoding="utf-8") as out:
            for e in error_lines:
                out.write(e + "\n")

        return error_count, error_lines

    except FileNotFoundError:
        print("❌ Log file not found!")
        return 0, []


count, errors = count_and_store_errors("system.log")

print("Total Errors Found:", count)
print("Error Lines Stored in: error_lines.txt")
print("Error Lines:", errors)

print("\n" + "-"*60 + "\n")

"""# TASK 02:
# read the csv data (employees)
# filter high salary employees
# write the result to new file
"""

print("Task 02: CSV Read + Filter High Salary + Write Output")

import csv

def filter_high_salary_employees(input_csv, output_csv, min_salary):
    high_salary_employees = []

    try:
        with open(input_csv, "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)

            for row in reader:
                salary = int(row["salary"])
                if salary >= min_salary:
                    high_salary_employees.append(row)

        with open(output_csv, "w", newline="", encoding="utf-8") as out:
            fieldnames = ["name", "department", "salary"]
            writer = csv.DictWriter(out, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(high_salary_employees)

        return high_salary_employees

    except FileNotFoundError:
        print("❌ employees.csv not found!")
        return []


filtered = filter_high_salary_employees("employees.csv", "high_salary_employees.csv", 60000)

print("High Salary Employees (>= 60000):")
for emp in filtered:
    print(emp)

print("\nOutput saved in: high_salary_employees.csv")

print("\n" + "-"*60 + "\n")

"""# TASK 03:
# generate daily report
"""

print("Task 03: Generate Daily Report")

from datetime import datetime

def generate_daily_report(report_filename="daily_report.txt"):
    now = datetime.now()

    # Read error count
    error_count, _ = count_and_store_errors("system.log")

    # Read employee salary stats
    salaries = []
    try:
        with open("employees.csv", "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)
            for row in reader:
                salaries.append(int(row["salary"]))
    except FileNotFoundError:
        salaries = []

    if salaries:
        highest = max(salaries)
        lowest = min(salaries)
        average = sum(salaries) / len(salaries)
    else:
        highest = lowest = average = 0

    report_text = f"""
DAILY REPORT
============
Date & Time: {now.strftime("%Y-%m-%d %H:%M:%S")}

SYSTEM LOG SUMMARY
------------------
Total Errors Found: {error_count}

EMPLOYEE SALARY SUMMARY
-----------------------
Highest Salary: {highest}
Lowest Salary: {lowest}
Average Salary: {average:.2f}
"""

    with open(report_filename, "w", encoding="utf-8") as file:
        file.write(report_text.strip())

    return report_text.strip()


report = generate_daily_report()
print(report)
print("\nReport saved as: daily_report.txt")

print("\n" + "-"*60 + "\n")

"""# MINI HANDS-ON QUESTIONS:
# handle division error
# handle missing file and log error
# validate user input (age, salary)
# create custom exception for atm withdrawal

# 1) Handle division error
"""

print("1) Handle Division Error")

def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "❌ Cannot divide by zero"

print("10 / 2 =", safe_divide(10, 2))
print("10 / 0 =", safe_divide(10, 0))

print("\n" + "-"*60 + "\n")

"""# 2) Handle missing file and log error"""

print("2) Handle Missing File and Log Error")

def read_file_with_logging(filename, log_file="error_log.txt"):
    try:
        with open(filename, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        msg = f"❌ File not found: {filename}\n"
        with open(log_file, "a", encoding="utf-8") as log:
            log.write(msg)
        return msg

print(read_file_with_logging("not_available.txt"))
print("Logged in: error_log.txt")

print("\n" + "-"*60 + "\n")

"""# 3) Validate user input (age, salary)

"""

print("3) Validate User Input (Age, Salary)")

def validate_age_salary(age, salary):
    try:
        age = int(age)
        salary = float(salary)

        if age <= 0 or age > 100:
            return "❌ Invalid age"
        if salary < 0:
            return "❌ Salary cannot be negative"

        return f"✅ Valid input: Age={age}, Salary={salary}"

    except ValueError:
        return "❌ Age must be integer and Salary must be numeric"

print(validate_age_salary("22", "50000"))
print(validate_age_salary("-5", "50000"))
print(validate_age_salary("abc", "50000"))

print("\n" + "-"*60 + "\n")

"""# 4) Custom exception for ATM withdrawal"""

print("4) Custom Exception for ATM Withdrawal")

class ATMWithdrawalError(Exception):
    pass

def atm_withdraw(balance, amount):
    if amount <= 0:
        raise ATMWithdrawalError("❌ Withdrawal amount must be greater than 0")
    if amount > balance:
        raise ATMWithdrawalError("❌ Insufficient balance")
    if amount % 100 != 0:
        raise ATMWithdrawalError("❌ Amount must be a multiple of 100")

    balance -= amount
    return balance


balance = 5000
amount = 1200

try:
    new_balance = atm_withdraw(balance, amount)
    print("Withdrawal Successful ✅")
    print("New Balance:", new_balance)
except ATMWithdrawalError as e:
    print("Withdrawal Failed:", e)

print("\n" + "-"*60 + "\n")

"""# PROJECT 1: Student Record Management
# filename: students.txt
# add students
# view students
# search students
"""

print("Project 1: Student Record Management")

STUDENT_FILE = "students.txt"

def add_student(name, roll_no):
    with open(STUDENT_FILE, "a", encoding="utf-8") as file:
        file.write(f"{roll_no},{name}\n")
    return "Student added ✅"

def view_students():
    try:
        with open(STUDENT_FILE, "r", encoding="utf-8") as file:
            data = file.readlines()

        if not data:
            return "No students found."

        return "".join(data)

    except FileNotFoundError:
        return "No student file found yet."

def search_student(roll_no):
    try:
        with open(STUDENT_FILE, "r", encoding="utf-8") as file:
            for line in file:
                r, n = line.strip().split(",", 1)
                if r == str(roll_no):
                    return f"✅ Found: Roll={r}, Name={n}"
        return "❌ Student not found"

    except FileNotFoundError:
        return "❌ Student file not found"

"""# Demo"""

print(add_student("Tarun", 101))
print(add_student("Neha", 102))

print("\nAll Students:\n", view_students())
print(search_student(102))
print(search_student(999))

print("\n" + "-"*60 + "\n")

"""# PROJECT 2: Word Counter Tool
# filename: summary.txt
# lines -> len(lines)
# words -> len(words)
# characters -> len(text)
"""

print("Project 2: Word Counter Tool")

SUMMARY_FILE = "summary.txt"

# Create a sample summary file
with open(SUMMARY_FILE, "w", encoding="utf-8") as f:
    f.write("Hello Tarun\nWelcome to Day 4\nPython file handling is useful.")

def word_counter_tool(filename):
    try:
        with open(filename, "r", encoding="utf-8") as file:
            text = file.read()

        lines = text.split("\n")
        words = text.split()
        characters = len(text)

        return len(lines), len(words), characters

    except FileNotFoundError:
        return 0, 0, 0


lines, words, chars = word_counter_tool(SUMMARY_FILE)

print("File:", SUMMARY_FILE)
print("Lines:", lines)
print("Words:", words)
print("Characters:", chars)

print("\n" + "-"*60 + "\n")

"""# PROJECT 3: Employee Salary Analyzer (CSV)
# filename: employees.csv
# highest, lowest, average salaries
# handle file not found error
"""

print("Project 3: Employee Salary Analyzer (CSV)")

def employee_salary_analyzer(csv_file):
    try:
        salaries = []
        with open(csv_file, "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)
            for row in reader:
                salaries.append(int(row["salary"]))

        if not salaries:
            return "No salary data found."

        highest = max(salaries)
        lowest = min(salaries)
        average = sum(salaries) / len(salaries)

        return highest, lowest, average

    except FileNotFoundError:
        return "❌ File not found error!"


result = employee_salary_analyzer("employees.csv")

print("Salary Analysis Result:", result)

print("\n" + "-"*60 + "\n")


print("✅ DAY 4 COMPLETED SUCCESSFULLY!")