# -*- coding: utf-8 -*-
"""Day_9_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hz7_9fRzJT_GU7NGs2wvhywpM1NBpFRs
"""

sales_data = [
    {"region": "East", "month": "Jan", "sales": 1000},
    {"region": "West", "month": "Jan", "sales": 1500},
    {"region": "East", "month": "Feb", "sales": 2000},
    {"region": "West", "month": "Feb", "sales": 1200},
]

from collections import defaultdict

region_total = defaultdict(int)
month_total = defaultdict(int)
month_count = defaultdict(int)

for record in sales_data:
    region_total[record["region"]] += record["sales"]
    month_total[record["month"]] += record["sales"]
    month_count[record["month"]] += 1

print("Total Sales Per Region:", dict(region_total))

print("Average Sales Per Month:")
for month in month_total:
    print(month, ":", month_total[month] / month_count[month])

best_region = max(region_total, key=region_total.get)
print("Best Performing Region:", best_region)

students = [
    {"name": "Anu", "marks": 85},
    {"name": "Ravi", "marks": 92},
    {"name": "Kiran", "marks": 78},
    {"name": "Meena", "marks": 90}
]

# Sort students by marks (descending order)
sorted_students = sorted(students, key=lambda x: x["marks"], reverse=True)

print("Student Ranking:\n")

rank = 1
for student in sorted_students:
    print(f"Rank {rank}: {student['name']} - {student['marks']} marks")
    rank += 1

products = [
    {"id": 101, "defects": 1},
    {"id": 102, "defects": 4},
    {"id": 103, "defects": 7},
    {"id": 104, "defects": 2}
]

print("Production Quality Report:\n")

for product in products:
    if product["defects"] <= 2:
        status = "Passed"
    elif 3 <= product["defects"] <= 5:
        status = "Needs Rework"
    else:
        status = "Rejected"

    print(f"Product {product['id']} - Defects: {product['defects']} - Status: {status}")

import numpy as np

# Base product prices
prices = np.array([100, 200, 300, 400])

# Tax percentages for 3 regions
tax_rates = np.array([0.05, 0.10, 0.15])  # 5%, 10%, 15%

# Apply broadcasting
final_prices = prices * (1 + tax_rates[:, np.newaxis])

print("Final Prices After Tax:\n")
print(final_prices)

print("Program Started")

import numpy as np

data = np.array([
    [101, 22, 2500, 1],
    [102, 30, 4000, 2],
    [103, 25, 1500, 1],
    [104, 35, 5000, 3],
    [105, 28, 3000, 2]
])

print("Total Customers:", data.shape[0])

purchase_column = data[:, 2]
print("Purchase Column:", purchase_column)

avg_purchase = np.mean(purchase_column)
print("Average Purchase:", avg_purchase)

print("Maximum Purchase:", np.max(purchase_column))
print("Minimum Purchase:", np.min(purchase_column))

above_avg_customers = data[purchase_column > avg_purchase]
print("Customers Above Average Purchase:")
print(above_avg_customers)

import numpy as np

# Create dataset
# Columns: employee_id, age, salary
# (Employee name stored separately because NumPy numeric array doesn't support mixed types easily)

employee_names = np.array(["Ravi", "Anu", "Kiran", "Meena", "Arjun"])

data = np.array([
    [101, 25, 30000],
    [102, 30, 45000],
    [103, 28, 40000],
    [104, 35, 55000],
    [105, 32, 50000]
])

# Extract columns
employee_id = data[:, 0]
age = data[:, 1]
salary = data[:, 2]

# 1. Total salary of all employees
total_salary = np.sum(salary)
print("Total Salary:", total_salary)

# 2. Minimum salary
print("Minimum Salary:", np.min(salary))

# 3. Maximum salary
print("Maximum Salary:", np.max(salary))

# 4. Average age
print("Average Age:", np.mean(age))

# 5. Total number of employees
print("Total Employees:", data.shape[0])

# 6. Correlation between age and salary
correlation = np.corrcoef(age, salary)
print("Correlation Matrix:\n", correlation)

print("Correlation between Age and Salary:", correlation[0,1])

from google.colab import drive
drive.mount('/content/drive')