# -*- coding: utf-8 -*-
"""Task_day_15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czbsOVPHDnIJ6tXXJGP_T4uW1AL1CSME

1.stock price movement---cummulative sum---np.cumsum(np.random.normal(mean,std,size))+100
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
mean = 0
std = 1
size = 100

# Generate stock prices
stock_price = np.cumsum(np.random.normal(mean, std, size)) + 100

# Plot
plt.figure()
plt.plot(stock_price)
plt.title("Stock Price Movement")
plt.xlabel("Days")
plt.ylabel("Stock Price")
plt.grid()
plt.show()

"""2.website traffic trend-----np.random.randint(start,stop,size)"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
start = 100      # minimum visitors
stop = 500       # maximum visitors
size = 30        # number of days

# Generate website traffic data
traffic = np.random.randint(start, stop, size)

# Plot
plt.figure()
plt.plot(traffic)
plt.title("Website Traffic Trend")
plt.xlabel("Days")
plt.ylabel("Number of Visitors")
plt.grid()
plt.show()

"""3.employee salary distribution---np.random.normal(mean,std,size)

"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
mean = 50000     # average salary
std = 8000       # standard deviation
size = 200       # number of employees

# Generate salary data
salary = np.random.normal(mean, std, size)

# Plot distribution
plt.figure()
plt.hist(salary, bins=20)
plt.title("Employee Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.grid()
plt.show()

"""4.loan default rate----np.choice([0,1])"""

import numpy as np
import matplotlib.pyplot as plt

# Generate loan default data
loan_default = np.random.choice([0, 1], size=100)

# Plot
plt.figure()
plt.hist(loan_default)
plt.title("Loan Default Rate")
plt.xlabel("Default (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.grid()
plt.show()

"""5.exam marks analysis----np.random.normal(loc,std,size)"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
loc = 70      # average marks
std = 10      # standard deviation
size = 100    # number of students

# Generate marks data
marks = np.random.normal(loc, std, size)

# Plot distribution
plt.figure()
plt.hist(marks, bins=15)
plt.title("Exam Marks Analysis")
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.grid()
plt.show()

"""6.temparature variation---use random,no. of days"""

import numpy as np
import matplotlib.pyplot as plt

# Number of days
days = 30

# Generate temperature data
temperature = np.random.normal(30, 5, days)

# Plot
plt.figure()
plt.plot(temperature)
plt.title("Temperature Variation")
plt.xlabel("Days")
plt.ylabel("Temperature (°C)")
plt.grid()
plt.show()

"""7.sales forecast vs actual---linspace,np.normal"""

import numpy as np
import matplotlib.pyplot as plt

# Months
months = np.linspace(1, 12, 12)

# Forecast sales (linear growth)
forecast = np.linspace(1000, 5000, 12)

# Actual sales (forecast + random variation)
actual = forecast + np.random.normal(0, 500, 12)

plt.figure()
plt.plot(months, forecast, label="Forecast")
plt.plot(months, actual, label="Actual")
plt.title("Sales Forecast vs Actual")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.legend()
plt.grid()
plt.show()

"""8. Inventory Stock Levels — np.random.randint"""

import numpy as np
import matplotlib.pyplot as plt

# Generate stock levels for 30 days
inventory = np.random.randint(50, 200, 30)

plt.figure()
plt.plot(inventory)
plt.title("Inventory Stock Levels")
plt.xlabel("Days")
plt.ylabel("Stock Quantity")
plt.grid()
plt.show()

"""9. Website Conversion Rate — Visitors & Conversions"""

import numpy as np
import matplotlib.pyplot as plt

# Generate visitors and conversions
visitors = np.random.randint(1000, 5000, 30)
conversions = np.random.randint(50, 300, 30)

# Conversion rate
conversion_rate = conversions / visitors

plt.figure()
plt.plot(conversion_rate)
plt.title("Website Conversion Rate")
plt.xlabel("Days")
plt.ylabel("Conversion Rate")
plt.grid()
plt.show()

"""10. COVID Cases Growth — np.cumsum(np.random.randint())"""

import numpy as np
import matplotlib.pyplot as plt

# Daily new cases
daily_cases = np.random.randint(100, 500, 50)

# Cumulative cases
total_cases = np.cumsum(daily_cases)

plt.figure()
plt.plot(total_cases)
plt.title("COVID Cases Growth")
plt.xlabel("Days")
plt.ylabel("Total Cases")
plt.grid()
plt.show()

"""11. Customer Churn Rate — np.random.choice"""

import numpy as np
import matplotlib.pyplot as plt

# 0 = Stayed, 1 = Churned
churn = np.random.choice([0, 1], size=200)

plt.figure()
plt.hist(churn)
plt.title("Customer Churn Rate")
plt.xlabel("Churn (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.grid()
plt.show()

"""12. E-commerce Order Analysis — np.random.randint"""

import numpy as np
import matplotlib.pyplot as plt

# Orders per day for 30 days
orders = np.random.randint(50, 500, 30)

plt.figure()
plt.plot(orders)
plt.title("E-commerce Order Analysis")
plt.xlabel("Days")
plt.ylabel("Number of Orders")
plt.grid()
plt.show()

"""# 1. What is Matplotlib? Explain about it?
Matplotlib is a Python library used for data visualization. It helps us to create different types of graphs like line graph, bar chart, histogram and scatter plot. It is mainly used in data analysis and scientific research to represent data visually. We can also customize the graph by adding title, labels, colors and styles.

# 2. Difference between plot() and scatterplot()
lot() is used to draw line graphs. It connects data points with lines and is mainly used to show trends.

scatter() is used to draw scatter plots. It shows individual data points without connecting them and is used to show relationship between two variables.

# 3. What is Pyplot? Explain about it
Pyplot is a module in Matplotlib. It provides simple functions to create graphs easily. By using pyplot we can draw graphs using commands like plt.plot(), plt.scatter() and plt.show(). It works similar to MATLAB style.

# 4. How to add labels and title?
We can add labels and title using:

plt.title("Title Name")  
plt.xlabel("X-axis Name")  
plt.ylabel("Y-axis Name")

# 5. What is the difference between figure and axes?
Figure is the complete window where the graph is drawn.

Axes is the area inside the figure where the actual graph is plotted. It contains x-axis and y-axis.

# 6. How to create multiple subplots?
We can create multiple subplots using plt.subplot() function.

Example:

plt.subplot(2,1,1)  
plt.plot(data1)

plt.subplot(2,1,2)  
plt.plot(data2)

# 7. What is the use of marker? What are the different markers?
Markers are used to show individual data points clearly in a graph.

Some markers are:
'o' circle  
's' square  
'^' triangle  
'*' star  
'.' point  
'x' cross  
'+' plus

# 8. How to customize colors?
We can customize colors using color parameter.

Example:

plt.plot(data, color='red')

# 9. How to handle large amount of data while visualization?
We can use sampling method, aggregation method, reduce data size, use transparency and proper scaling.

# 10. Which plot is used for performing trends in the data?
Line plot is used for showing trends in the data.

# 11. Which plot is used for data distributions?
Histogram is used to show data distribution.

# 12. How to display grid?
We can display grid using:

plt.grid()

# 13. How to change line color?

We can change line color using:

plt.plot(data, color='green')

# 14. What are the different styles available in line?

'-' solid line  
'--' dashed line  
':' dotted line  
'-.' dash-dot line
"""