# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ekm3zCo_kpZQHt_u93OoVXOQi9EXKrY5
"""

print("✅ Python Tasks - Final Solved Version\n")

"""
# 1) User Login Access Control (Very Common in Internships)
# Task: Check whether a user can log in based on:
# - username
# - account status

"""

print("1) User Login Access Control")

username = "tarun"
account_status = "active"

if account_status == "active":
    print(f"Login allowed for user: {username}")
else:
    print(f"Login denied for user: {username} (Status: {account_status})")

print("\n" + "-"*60 + "\n")

"""# 2) Internship Eligibility Checker (HR Automation)
# Task: Check eligibility based on:
# - CGPA
# - Year of study
# - Skill test score
"""

print("2) Internship Eligibility Checker")

cgpa = 7.4
year_of_study = 3
skill_test_score = 68

if cgpa >= 7.0 and year_of_study >= 3 and skill_test_score >= 60:
    print("Eligible for Internship ✅")
else:
    print("Not Eligible for Internship ❌")

print("\n" + "-"*60 + "\n")

"""# 3) E-Commerce Discount Logic  
# Task: Apply discount based on cart value
"""

print("3) E-Commerce Discount Logic")

cart_value = 5200

if cart_value >= 10000:
    discount = 20
elif cart_value >= 5000:
    discount = 10
elif cart_value >= 2000:
    discount = 5
else:
    discount = 0

final_price = cart_value - (cart_value * discount / 100)

print(f"Cart Value: ₹{cart_value}")
print(f"Discount: {discount}%")
print(f"Final Price: ₹{final_price}")

print("\n" + "-"*60 + "\n")

"""# 4) API Response Status Checker  
# Task: Display message based on API status code
"""

print("4) API Response Status Checker")

status_code = 404

if status_code == 200:
    print("Success: API request completed ✅")
elif status_code == 201:
    print("Created: Resource created successfully ✅")
elif status_code == 400:
    print("Bad Request: Invalid input ❌")
elif status_code == 401:
    print("Unauthorized: Authentication required ❌")
elif status_code == 403:
    print("Forbidden: Access denied ❌")
elif status_code == 404:
    print("Not Found: Resource not found ❌")
elif status_code >= 500:
    print("Server Error: Try again later ❌")
else:
    print("Unknown status code")

print("\n" + "-"*60 + "\n")

"""# 5) Student Result Processing  
# Task: Assign grade based on marks
"""

print("5) Student Result Processing")

marks = 82

if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
elif marks >= 60:
    grade = "C"
elif marks >= 50:
    grade = "D"
else:
    grade = "Fail"

print(f"Marks: {marks}")
print(f"Grade: {grade}")

print("\n" + "-"*60 + "\n")

"""# 6) User Login & Role Validation System
# Task: Allow login only if the user exists and has a valid role
# Concepts: Variables, List, Conditions
"""

print("6) User Login & Role Validation System")

users = ["tarun", "animesh", "rahul", "neha"]
valid_roles = ["admin", "user", "manager"]

input_user = "tarun"
input_role = "admin"

if input_user in users and input_role in valid_roles:
    print(f"Login Successful ✅ | User: {input_user} | Role: {input_role}")
else:
    print("Login Failed ❌ (Invalid user or role)")

print("\n" + "-"*60 + "\n")

"""# 7) Internship Eligibility Checker  
# Task: Check if a student is eligible for internship.
# Concepts: Variables, Dictionary, Conditions
"""

print("7) Internship Eligibility Checker (Dictionary)")

student = {
    "name": "Tarun",
    "cgpa": 7.6,
    "year": 3,
    "skill_score": 72
}

if student["cgpa"] >= 7.0 and student["year"] >= 3 and student["skill_score"] >= 60:
    print(f"{student['name']} is Eligible for Internship ✅")
else:
    print(f"{student['name']} is Not Eligible for Internship ❌")

print("\n" + "-"*60 + "\n")

"""# 8) E-Commerce Discount Engine
# Task: Apply discount based on cart value and membership.
# Concepts: Variables, Dictionary, Conditions
"""

print("8) E-Commerce Discount Engine")

order = {
    "cart_value": 8500,
    "membership": "gold"   # none / silver / gold / platinum
}

cart = order["cart_value"]
membership = order["membership"]

discount = 0

if cart >= 10000:
    discount = 20
elif cart >= 5000:
    discount = 10
elif cart >= 2000:
    discount = 5

# Extra membership discount
if membership == "silver":
    discount += 2
elif membership == "gold":
    discount += 5
elif membership == "platinum":
    discount += 8

# Cap discount at 30%
if discount > 30:
    discount = 30

final_price = cart - (cart * discount / 100)

print(f"Cart: ₹{cart}")
print(f"Membership: {membership}")
print(f"Total Discount: {discount}%")
print(f"Final Payable: ₹{final_price}")

print("\n" + "-"*60 + "\n")

"""# 9) Bank Account Balance Validation
# Task: Check withdrawal eligibility.
# Concepts: Variables, Dictionary, Conditional logic
"""

print("9) Bank Account Balance Validation")

account = {
    "name": "Tarun",
    "balance": 4500
}

withdraw_amount = 5000

if withdraw_amount <= account["balance"]:
    account["balance"] -= withdraw_amount
    print(f"Withdrawal Successful ✅ New Balance: ₹{account['balance']}")
else:
    print("Withdrawal Failed ❌ Insufficient Balance")

print("\n" + "-"*60 + "\n")



"""# 10) Attendance Status System
# Task: Check student attendance status.
# Concepts: Variables, List, Conditions
"""

print("10) Attendance Status System")

students_present = ["tarun", "rahul", "neha"]

student_name = "animesh"

if student_name in students_present:
    print(f"{student_name} is Present ✅")
else:
    print(f"{student_name} is Absent ❌")

print("\n" + "-"*60 + "\n")



"""# 11) Employee Attendance Counter
# Task: Count how many employees are present.
# Concepts: List, for loop, Variables
"""

print("11) Employee Attendance Counter")

attendance_list = ["P", "A", "P", "P", "A", "P", "A", "P"]

present_count = 0

for status in attendance_list:
    if status == "P":
        present_count += 1

print(f"Total Employees: {len(attendance_list)}")
print(f"Present Employees: {present_count}")

print("\n" + "-"*60 + "\n")



"""# 12) Internship Shortlisting System
# Task: Shortlist students with CGPA ≥ 7.
# Concepts: List of dictionaries, for loop
"""

print("12) Internship Shortlisting System")

students = [
    {"name": "Tarun", "cgpa": 7.8},
    {"name": "Rahul", "cgpa": 6.9},
    {"name": "Neha", "cgpa": 8.1},
    {"name": "Animesh", "cgpa": 7.0},
]

shortlisted = []

for s in students:
    if s["cgpa"] >= 7.0:
        shortlisted.append(s["name"])

print("Shortlisted Students ✅:", shortlisted)

print("\n" + "-"*60 + "\n")

"""# 13) E-Commerce Cart Total Calculator
# Task: Calculate total cart value.
# Concepts: List, for loop, Variables
"""

print("13) E-Commerce Cart Total Calculator")

cart_items = [1200, 500, 350, 900, 1500]

total = 0

for price in cart_items:
    total += price

print("Cart Items:", cart_items)
print("Total Cart Value: ₹", total)

print("\n" + "-"*60 + "\n")

"""# 14) Product Inventory Check
# Task: Display available products only.
# Concepts: Dictionary, for loop
"""

print("14) Product Inventory Check")

inventory = {
    "Laptop": 5,
    "Mouse": 0,
    "Keyboard": 12,
    "Monitor": 0,
    "USB Cable": 7
}

print("Available Products ✅:")
for product, qty in inventory.items():
    if qty > 0:
        print(f"- {product} (Qty: {qty})")

print("\n" + "-"*60 + "\n")

"""# 15) Student Marks Average Calculator
# Task: Calculate average marks.
# Concepts: List, for loop, Variables
"""

print("15) Student Marks Average Calculator")

marks_list = [78, 85, 92, 67, 74]

sum_marks = 0

for m in marks_list:
    sum_marks += m

average = sum_marks / len(marks_list)

print("Marks:", marks_list)
print("Average Marks:", average)

print("\n" + "-"*60 + "\n")

"""# 16) User Access Review System
# Task: List users with admin access.
# Concepts: Dictionary, for loop
"""

print("16) User Access Review System")

user_access = {
    "tarun": "admin",
    "rahul": "user",
    "neha": "admin",
    "animesh": "manager",
    "sneha": "user"
}

print("Users with Admin Access ✅:")
for user, role in user_access.items():
    if role == "admin":
        print("-", user)

print("\n✅ All tasks executed successfully!")